Added TraceIdStore implementation - to protect against potential fraud threats
piangles/Gateway pull request #7
Opened 2022-10-17 20:19 UTC by harikareddy1023

2022-10-17 20:23 UTC, harikareddy1023 commented on src/main/java/org/piangles/gateway/requests/CacheTraceIdStore.java
> +	}
TODO where does the componentId go for Gateway Config

2022-10-19 19:29 UTC, saradhiZuro requested changes

2022-10-19 19:29 UTC, saradhiZuro commented on src/main/java/org/piangles/gateway/GatewayConfiguration.java
> +	public boolean getCacheTraceIdStoreEnabled()
Please rename getCacheTraceIdStoreEnabled to isCacheTraceIdStoreEnabled

2022-10-19 19:29 UTC, saradhiZuro commented on src/main/java/org/piangles/gateway/requests/RequestProcessingManager.java
> +				sessionService.unregister(clientDetails.getSessionDetails().getUserId(), clientDetails.getSessionDetails().getSessionId());
We need to close connection.

2022-10-19 19:29 UTC, saradhiZuro commented on src/main/java/org/piangles/gateway/requests/CacheTraceIdStore.java
> +	}
We need a private method to createKey(String traceId) {return "TraceId:" + traceId;}

2022-10-19 20:35 UTC, saradhiZuro approved these changes

2022-10-19 20:36 UTC, merged